%% Allow clients to publish and subscribe strictly to their own channel
{allow, all, subscribe, ["users/${username}/devices/${clientid}/command/#"]}.
{allow, all, publish, ["users/${username}/devices/${clientid}/status"]}.
{allow, all, subscribe, ["users/${username}/devices/#/status"]}.
{allow, all, subscribe, ["users/${username}/devices/#/telemetry/#"]}.
{allow, all, publish, ["users/${username}/devices/${clientid}/telemetry/#"]}.
{allow, all, subscribe, ["users/${username}/devices/${clientid}/telemetry/#"]}.
{allow, all, subscribe, ["ota/updates/#"]}.
%% Deny everything else by default
{deny, all}.