[env:esp32s3_mini-test]
platform = espressif32
framework = arduino
board = esp32-s3-devkitc-1
board_build.flash_size = 4MB
board_upload.flash_size = 4MB
board_build.partitions = ota_partitions.csv
build_flags =
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DARDUINO_USB_MSC_ON_BOOT=0
    -DARDUINO_USB_DFU_ON_BOOT=0
	-D ENV_TEST
	-D DEVICE_TYPE_STR=\"ESP32S3_Mini\"
    -D DEVICE_VERSION_STR=\"v2.0.113\"
lib_deps =
	knolleary/PubSubClient@^2.8
	adafruit/Adafruit NeoPixel@^1.15.4
	bblanchon/ArduinoJson@^7.2.2
	links2004/WebSockets@^2.7.3
	hideakitai/MQTTPubSubClient@^0.3.2
	ferdiu/ESP32ProvisionToolkit@^1.0.1
	tzapu/WiFiManager@^2.0.17
	paulstoffregen/OneWire@^2.3.8
	milesburton/DallasTemperature@^4.0.6
; Adjust upload and monitor speeds
upload_speed = 921600
monitor_speed = 115200
[env:esp32s3_mini-prod]
platform = espressif32
framework = arduino
board = esp32-s3-devkitc-1
board_build.flash_size = 4MB
board_upload.flash_size = 4MB
; Fixes the missing file build error
board_build.partitions = ota_partitions.csv
build_flags =
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DARDUINO_USB_MSC_ON_BOOT=0
    -DARDUINO_USB_DFU_ON_BOOT=0
	-D ENV_PROD
	-D DEVICE_TYPE_STR=\"ESP32S3_Mini\"
	-D DEVICE_VERSION_STR=\"v2.0.113\"
lib_deps =
	knolleary/PubSubClient@^2.8
	adafruit/Adafruit NeoPixel@^1.15.4
	bblanchon/ArduinoJson@^7.2.2
	links2004/WebSockets@^2.7.3
	hideakitai/MQTTPubSubClient@^0.3.2
	ferdiu/ESP32ProvisionToolkit@^1.0.1
	tzapu/WiFiManager@^2.0.17
	paulstoffregen/OneWire@^2.3.8
	milesburton/DallasTemperature@^4.0.6
upload_speed = 921600
monitor_speed = 115200
[env:4d_systems_esp32s3_gen4_r8n16-test]
platform = espressif32
board = 4d_systems_esp32s3_gen4_r8n16
framework = arduino
monitor_speed = 115200
monitor_filters = esp32_exception_decoder
build_flags =
	-D ARDUINO_USB_MODE=0
	-D ARDUINO_USB_CDC_ON_BOOT=0
	-D ARDUINO_EVENT_RUNNING_NO_AFFINITY
	-D ENV_TEST
	-D DEVICE_TYPE_STR=\"ESP32S3_MultiSocket\"
	-D DEVICE_VERSION_STR=\"v2.0.113\"
lib_deps =
	knolleary/PubSubClient@^2.8
	adafruit/Adafruit NeoPixel@^1.15.4
	bblanchon/ArduinoJson@^7.2.2
	links2004/WebSockets@^2.7.3
	hideakitai/MQTTPubSubClient@^0.3.2
	ferdiu/ESP32ProvisionToolkit@^1.0.1
	tzapu/WiFiManager@^2.0.17
	paulstoffregen/OneWire@^2.3.8
	milesburton/DallasTemperature@^4.0.6
[env:4d_systems_esp32s3_gen4_r8n16-prod]
platform = espressif32
board = 4d_systems_esp32s3_gen4_r8n16
framework = arduino
monitor_speed = 115200
monitor_filters = esp32_exception_decoder
build_flags =
	-D ARDUINO_USB_MODE=0
	-D ARDUINO_USB_CDC_ON_BOOT=0
	-D ARDUINO_EVENT_RUNNING_NO_AFFINITY
	-D ENV_PROD
	-D DEVICE_TYPE_STR=\"ESP32S3_MultiSocket\"
	-D DEVICE_VERSION_STR=\"v2.0.113\"
lib_deps =
	knolleary/PubSubClient@^2.8
	adafruit/Adafruit NeoPixel@^1.15.4
	bblanchon/ArduinoJson@^7.2.2
	links2004/WebSockets@^2.7.3
	hideakitai/MQTTPubSubClient@^0.3.2
	ferdiu/ESP32ProvisionToolkit@^1.0.1
	tzapu/WiFiManager@^2.0.17
	paulstoffregen/OneWire@^2.3.8
	milesburton/DallasTemperature@^4.0.6
[env:esp32wrover_e-test]
platform = espressif32
framework = arduino
board = esp32dev
board_build.flash_size = 4MB
board_upload.flash_size = 4MB
board_build.partitions = wrover_e_partitions.csv
board_build.arduino.memory_type = qio_qspi
monitor_speed = 115200
monitor_filters = esp32_exception_decoder
build_flags =
    -D ENV_TEST
    -D ONBOARD_LED_PIN=2
    -D BOARD_HAS_PSRAM
    -mfix-esp32-psram-cache-issue
    -D DEVICE_TYPE_STR=\"ESP32S3_Wrover\"
    -D  DEVICE_VERSION_STR=\"v2.0.113\"
lib_deps =
    knolleary/PubSubClient@^2.8
    adafruit/Adafruit NeoPixel@^1.15.4
    bblanchon/ArduinoJson@^7.2.2
    links2004/WebSockets@^2.7.3
    hideakitai/MQTTPubSubClient@^0.3.2
    ferdiu/ESP32ProvisionToolkit@^1.0.1
    tzapu/WiFiManager@^2.0.17
    paulstoffregen/OneWire@^2.3.8   
    milesburton/DallasTemperature@^4.0.6
upload_speed = 921600
[env:esp32wrover_e-prod]
platform = espressif32
framework = arduino
board = esp32dev
board_build.flash_size = 4MB
board_upload.flash_size = 4MB
board_build.partitions = wrover_e_partitions.csv
board_build.arduino.memory_type = qio_qspi
monitor_speed = 115200
monitor_filters = esp32_exception_decoder
build_flags =
    -D ENV_PROD
    -D ONBOARD_LED_PIN=2
    -D BOARD_HAS_PSRAM
    -mfix-esp32-psram-cache-issue
    -D DEVICE_TYPE_STR=\"ESP32S3_Wrover\"
    -D  DEVICE_VERSION_STR=\"v2.0.113\"
lib_deps =
    knolleary/PubSubClient@^2.8
    adafruit/Adafruit NeoPixel@^1.15.4
    bblanchon/ArduinoJson@^7.2.2
    links2004/WebSockets@^2.7.3
    hideakitai/MQTTPubSubClient@^0.3.2
    ferdiu/ESP32ProvisionToolkit@^1.0.1
    tzapu/WiFiManager@^2.0.17
    paulstoffregen/OneWire@^2.3.8
    milesburton/DallasTemperature@^4.0.6
upload_speed = 921600

[env:esp32s3_cam-test]
platform = espressif32
framework = arduino
board = esp32-s3-devkitc-1
board_build.flash_size = 8MB
board_upload.flash_size = 8MB
board_build.partitions = s3_cam_partitions.csv
board_build.arduino.memory_type = qio_opi
monitor_speed = 115200
monitor_filters = esp32_exception_decoder
build_flags =
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DARDUINO_USB_MSC_ON_BOOT=0
    -DARDUINO_USB_DFU_ON_BOOT=0
    -D ENV_TEST
    -D DEVICE_TYPE_STR=\"ESP32S3_Cam\"
    -D DEVICE_VERSION_STR=\"v2.0.113\"
    -D BOARD_HAS_PSRAM
    -D HAS_CAMERA
    -D PWDN_GPIO_NUM=-1
    -D RESET_GPIO_NUM=-1
    -D XCLK_GPIO_NUM=15
    -D SIOD_GPIO_NUM=4
    -D SIOC_GPIO_NUM=5
    -D Y9_GPIO_NUM=16
    -D Y8_GPIO_NUM=17
    -D Y7_GPIO_NUM=18
    -D Y6_GPIO_NUM=12
    -D Y5_GPIO_NUM=10
    -D Y4_GPIO_NUM=8
    -D Y3_GPIO_NUM=9
    -D Y2_GPIO_NUM=11
    -D VSYNC_GPIO_NUM=6
    -D HREF_GPIO_NUM=7
    -D PCLK_GPIO_NUM=13
lib_deps =
    knolleary/PubSubClient@^2.8
    adafruit/Adafruit NeoPixel@^1.15.4
    bblanchon/ArduinoJson@^7.2.2
    links2004/WebSockets@^2.7.3
    hideakitai/MQTTPubSubClient@^0.3.2
    ferdiu/ESP32ProvisionToolkit@^1.0.1
    tzapu/WiFiManager@^2.0.17
    paulstoffregen/OneWire@^2.3.8
    milesburton/DallasTemperature@^4.0.6
    espressif/esp32-camera
upload_speed = 921600
[env:esp32s3_cam-prod]
platform = espressif32
framework = arduino
board = esp32-s3-devkitc-1
board_build.flash_size = 8MB
board_upload.flash_size = 8MB
board_build.partitions = s3_cam_partitions.csv
board_build.arduino.memory_type = qio_opi
monitor_speed = 115200
monitor_filters = esp32_exception_decoder
build_flags =
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DARDUINO_USB_MSC_ON_BOOT=0
    -DARDUINO_USB_DFU_ON_BOOT=0
    -D ENV_PROD
    -D DEVICE_TYPE_STR=\"ESP32S3_Cam\"
    -D  DEVICE_VERSION_STR=\"v2.0.113\"
    -D BOARD_HAS_PSRAM
    -D HAS_CAMERA
    -D PWDN_GPIO_NUM=-1
    -D RESET_GPIO_NUM=-1
    -D XCLK_GPIO_NUM=15
    -D SIOD_GPIO_NUM=4
    -D SIOC_GPIO_NUM=5
    -D Y9_GPIO_NUM=16
    -D Y8_GPIO_NUM=17
    -D Y7_GPIO_NUM=18
    -D Y6_GPIO_NUM=12
    -D Y5_GPIO_NUM=10
    -D Y4_GPIO_NUM=8
    -D Y3_GPIO_NUM=9
    -D Y2_GPIO_NUM=11
    -D VSYNC_GPIO_NUM=6
    -D HREF_GPIO_NUM=7
    -D PCLK_GPIO_NUM=13
lib_deps =
    knolleary/PubSubClient@^2.8
    adafruit/Adafruit NeoPixel@^1.15.4
    bblanchon/ArduinoJson@^7.2.2
    links2004/WebSockets@^2.7.3
    hideakitai/MQTTPubSubClient@^0.3.2
    ferdiu/ESP32ProvisionToolkit@^1.0.1
    tzapu/WiFiManager@^2.0.17
    paulstoffregen/OneWire@^2.3.8
    milesburton/DallasTemperature@^4.0.6
    espressif/esp32-camera
upload_speed = 921600
