apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-proxy-manager
  namespace: iot-system
spec:
  replicas: 1 # Must be 1 to avoid database locking issues with SQLite
  selector:
    matchLabels:
      app: npm
  template:
    metadata:
      labels:
        app: npm
    spec:
      containers:
      - name: npm
        image: jc21/nginx-proxy-manager:latest
        ports:
        - containerPort: 80
        - containerPort: 81
        - containerPort: 443
        - containerPort: 1883 # Exposing the port for MQTT Streams
        volumeMounts:
        - name: npm-data
          mountPath: /data
        - name: npm-data # LetsEncrypt certs are also stored in /data by default in newer NPM versions, but check docs if you need /etc/letsencrypt separate
          mountPath: /etc/letsencrypt
      volumes:
      - name: npm-data
        persistentVolumeClaim:
          claimName: npm-data-pvc
---